version: 0.0
os: linux
files:
  - source: /
    destination: /srv/chrisipowell_api
hooks:
  AfterInstall:
    - locaton: after_install.sh
  ApplicationStart:
    - location: start.sh
  ApplicationStop:
    - location: stop.sh
  VerifyApplication:
    - location: ping.sh
