version: 0.0
os: linux
files:
  - source: /
    destination: /srv/chrisipowell_api
hooks:
  AfterInstall:
    - location: after_install.sh
  ApplicationStart:
    - location: start.sh
  VerifyApplication:
    - location: ping.sh
